### ISSUE TITLE
Change apikey & add config.json to .gitignore

### ISSUE THREAD

**Issue by katrinleinweber** [oshipston/reviewNet#1]
According to [ElsevierDev's advice](https://github.com/ElsevierDev/elsapy/blob/master/CONFIG.md), that file should not be included in a public git repo. Yours currently is, so please consider changing your apikey now, and then [stop tracking it in your git repo](https://duckduckgo.com/?q=git+remove+tracked+file).

**Comment by oshipston** [comment]
Ah thank you so much, I had forgotten I had tracked this repo to be honest. Thank you!

**Comment by katrinleinweber** [comment]
You're welcome :-)
